url: "sarahpethani.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sarah Pethani" # the name of your site, e.g. ACME Corp.

defaults:
  - scope:
      path: "assets/img/artwork/watercolor"
    values:
      watercolor-image: true
  - scope:
      path: "assets/img/artwork/digital"
    values:
      digital-image: true
  - scope:
      path: "assets/img/artwork/other"
    values:
      other-image: true
  
